import { classPrefix } from '../utils/helpers';

type ColorKey = 'primary' | 'accent' | 'surface' | 'success' | 'warning' | 'danger' | 'info';

const colorPalettes: ColorKey[] = [
  'primary',
  'accent',
  'surface',
  'success',
  'warning',
  'danger',
  'info',
];

const colors = {
  accent: {
    '100': `rgb(var(--${classPrefix}-accent-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-accent-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-accent-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-accent-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-accent-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-accent-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-accent-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-accent-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-accent-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-accent-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-accent-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-accent-base) / <alpha-value>)`,
  },

  danger: {
    '100': `rgb(var(--${classPrefix}-danger-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-danger-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-danger-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-danger-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-danger-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-danger-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-danger-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-danger-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-danger-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-danger-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-danger-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-danger-base) / <alpha-value>)`,
  },

  info: {
    '100': `rgb(var(--${classPrefix}-info-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-info-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-info-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-info-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-info-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-info-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-info-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-info-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-info-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-info-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-info-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-info-base) / <alpha-value>)`,
  },

  primary: {
    '100': `rgb(var(--${classPrefix}-primary-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-primary-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-primary-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-primary-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-primary-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-primary-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-primary-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-primary-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-primary-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-primary-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-primary-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-primary-base) / <alpha-value>)`,
  },

  semantic: {
    accent: `rgb(var(--${classPrefix}-adaptive-accent) / <alpha-value>)`,
    bg: `rgb(var(--${classPrefix}-adaptive-primary) / <alpha-value>)`,
    bgAlt: `rgb(var(--${classPrefix}-adaptive-surface) / <alpha-value>)`,
    border: `rgb(var(--${classPrefix}-inverse-surface) / <alpha-value>)`,
    borderAlt: `rgb(var(--${classPrefix}-adaptive-surface) / <alpha-value>)`,
    danger: `rgb(var(--${classPrefix}-adaptive-danger) / <alpha-value>)`,
    info: `rgb(var(--${classPrefix}-adaptive-info) / <alpha-value>)`,
    inverse: `rgb(var(--${classPrefix}-inverse-primary) / <alpha-value>)`,
    inverseText: `rgb(var(--${classPrefix}-adaptive-primary) / <alpha-value>)`,
    primary: `rgb(var(--${classPrefix}-adaptive-primary) / <alpha-value>)`,
    success: `rgb(var(--${classPrefix}-adaptive-success) / <alpha-value>)`,
    surface: `rgb(var(--${classPrefix}-adaptive-surface) / <alpha-value>)`,
    text: `rgb(var(--${classPrefix}-inverse-surface) / <alpha-value>)`,
    textAlt: `rgb(var(--${classPrefix}-inverse-primary) / <alpha-value>)`,
    textMuted: `rgb(var(--${classPrefix}-inverse-surface) / <alpha-value>)`,
    textMutedAlt: `rgb(var(--${classPrefix}-inverse-primary) / <alpha-value>)`,
    warning: `rgb(var(--${classPrefix}-adaptive-warning) / <alpha-value>)`,
  },

  success: {
    '100': `rgb(var(--${classPrefix}-success-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-success-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-success-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-success-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-success-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-success-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-success-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-success-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-success-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-success-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-success-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-success-base) / <alpha-value>)`,
  },

  surface: {
    '100': `rgb(var(--${classPrefix}-surface-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-surface-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-surface-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-surface-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-surface-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-surface-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-surface-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-surface-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-surface-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-surface-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-surface-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-surface-base) / <alpha-value>)`,
  },

  warning: {
    '100': `rgb(var(--${classPrefix}-warning-100) / <alpha-value>)`,
    '200': `rgb(var(--${classPrefix}-warning-200) / <alpha-value>)`,
    '300': `rgb(var(--${classPrefix}-warning-300) / <alpha-value>)`,
    '400': `rgb(var(--${classPrefix}-warning-400) / <alpha-value>)`,
    '50': `rgb(var(--${classPrefix}-warning-50) / <alpha-value>)`,
    '500': `rgb(var(--${classPrefix}-warning-500) / <alpha-value>)`,
    '600': `rgb(var(--${classPrefix}-warning-600) / <alpha-value>)`,
    '700': `rgb(var(--${classPrefix}-warning-700) / <alpha-value>)`,
    '800': `rgb(var(--${classPrefix}-warning-800) / <alpha-value>)`,
    '900': `rgb(var(--${classPrefix}-warning-900) / <alpha-value>)`,
    '950': `rgb(var(--${classPrefix}-warning-950) / <alpha-value>)`,
    base: `rgb(var(--${classPrefix}-warning-base) / <alpha-value>)`,
  },
} as const;

export { colorPalettes, colors };
export type { ColorKey };
