#:tombi schema.strict = false

# monorepo_root = true

# [monorepo]
# config_roots = ["apps/*", "packages/*"]

[settings]
experimental = true

[bootstrap.mise_shell_activate]
zprofile = { enabled = true, mode = "shims" }
zshrc = { enabled = true, mode = "activate" }
bash_profile = { enabled = true, mode = "shims" }
bashrc = { enabled = true, mode = "activate" }

[tools]
gh = "2.100.0"
dagger = "0.21.9"
jq = "1.7.1"
# viteplus = "0.2.7"

[env]
_.file = ".env"

[task_config]
dir = "{{config_root}}"

[tasks]
hello = { description = "A simple hello task for testing", run = "echo hello from mise: ${TEST_VAR}" }
