packages:
  - apps/*
  - packages/*

allowBuilds:
  '@scarf/scarf': true
  esbuild: true

catalog:
  '@emnapi/core': npm:@emnapi/core@1.9.2
  '@emnapi/runtime': npm:@emnapi/runtime@1.9.2
  '@iconify-json/logos': npm:@iconify-json/logos@1.2.1
  '@iconify-json/ph': npm:@iconify-json/ph@1.2.2
  '@trpc/client': npm:@trpc/client@11.17.0
  '@trpc/server': npm:@trpc/server@11.17.0
  '@types/cors': npm:@types/cors@2.8.19
  '@types/crypto-js': npm:@types/crypto-js@4.2.0
  '@types/culori': npm:@types/culori@4.0.1
  '@types/express': npm:@types/express@5.0.6
  '@types/express-serve-static-core': npm:@types/express-serve-static-core@5.1.1
  '@types/node': npm:@types/node@25.5.2
  '@types/react': npm:@types/react@19.2.14
  '@types/react-dom': npm:@types/react-dom@19.2.3
  '@types/supertest': npm:@types/supertest@7.2.0
  '@types/swagger-ui-express': npm:@types/swagger-ui-express@4.1.8
  '@types/uuid': npm:@types/uuid@11.0.0
  '@types/wcwidth': npm:@types/wcwidth@1.0.1
  '@typescript/native-preview': npm:@typescript/native-preview@7.0.0-dev.20260405.1
  '@unocss/preset-wind3': npm:@unocss/preset-wind3@66.6.7
  '@unocss/transformer-directives': npm:@unocss/transformer-directives@66.6.7
  '@unocss/transformer-variant-group': npm:@unocss/transformer-variant-group@66.6.7
  '@vitejs/plugin-react': npm:@vitejs/plugin-react@6.0.1
  '@vitest/coverage-v8': npm:@vitest/coverage-v8@4.1.2
  axios: npm:axios@1.16.0
  bumpp: npm:bumpp@11.0.1
  chalk: npm:chalk@5.6.2
  class-variance-authority: npm:class-variance-authority@0.7.1
  cors: npm:cors@2.8.6
  crypto-js: npm:crypto-js@4.2.0
  culori: npm:culori@4.0.2
  express: npm:express@5.2.1
  express-list-endpoints: npm:express-list-endpoints@7.1.1
  fast-glob: npm:fast-glob@3.3.3
  helmet: npm:helmet@8.1.0
  lodash.isplainobject: npm:lodash.isplainobject@4.0.6
  mock-express: npm:mock-express@2.0.0
  openapi-trpc: npm:openapi-trpc@0.2.1
  openapi-types: npm:openapi-types@12.1.3
  picocolors: npm:picocolors@1.1.1
  react: npm:react@19.2.4
  react-dom: npm:react-dom@19.2.4
  redact-object: npm:redact-object@4.0.4
  rimraf: npm:rimraf@6.1.3
  rotating-file-stream: npm:rotating-file-stream@3.2.9
  superjson: npm:superjson@2.2.6
  supertest: npm:supertest@7.2.2
  swagger-autogen: npm:swagger-autogen@2.23.7
  swagger-ui-express: npm:swagger-ui-express@5.0.1
  trpc-openapi: npm:trpc-openapi@1.2.0
  trpc-playground: npm:trpc-playground@1.0.4
  ts-morph: npm:ts-morph@28.0.0
  tsx: npm:tsx@4.21.0
  typescript: npm:typescript@6.0.2
  unocss: npm:unocss@66.6.7
  uuid: npm:uuid@11.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.1.20
  vite-plugin-node: npm:vite-plugin-node@8.0.0
  vite-plus: npm:vite-plus@0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.20
  wcwidth: npm:wcwidth@1.0.1
  zod: npm:zod@4.4.3

catalogMode: prefer

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
