name = "lightproject-frontend"
compatibility_date = "2026-08-26"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
