#!/usr/bin/env bash
#MISE description="Run type checking, formatting, linting, building, and tests"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"
rootDir="$(pwd)"

cache="${1:-"true"}"
install="${2:-"false"}"

function executeCommand() {
  local arguments=("${@}")

  local outputsDir="${rootDir}/.outputs"
  mkdir -p "${outputsDir}"

  local commandName="${arguments[*]}"

  local isBuildCommand="false"
  case "${commandName}" in
    "vp run -r build"*)
      isBuildCommand="true"
      ;;
  esac

  local commandSuccess="false"

  echo "✨ Executing executed command: \`${commandName}\`"

  "${arguments[@]}" && commandSuccess="true" || commandSuccess="false"

  if [[ "${commandSuccess}" == "true" ]]; then
    echo "✅ Successfully executed command: \`${commandName}\`"
    
    if [[ "${isBuildCommand}" == "true" ]]; then
      local stylesGeneratedJsonFile="${rootDir}/packages/design-system/tmp/compile/styles.json"
      local stylesMasterJsonFile="${outputsDir}/styles.json"
      
      if [[ -f "${stylesGeneratedJsonFile}" ]]; then
        cp "${stylesGeneratedJsonFile}" "${stylesMasterJsonFile}"
        vp format --write "${stylesMasterJsonFile}"
        echo "✅ Saved styles to ${stylesMasterJsonFile}"
      fi
    fi
  else
    echo "❌ Failed to execute command: \`${commandName}\`"
    exit 1
  fi
}

if [[ "${cache}" == "false" ]]; then
  vp cache clean
fi

if [[ "${install}" == "true" ]]; then
  vp install --frozen-lockfile
fi

executeCommand vp run -r madge
executeCommand vp run -r root --fix
executeCommand vp run -r check --fix
executeCommand vp run -r format --write
executeCommand vp run -r lint --fix
executeCommand vp run -r type-check
executeCommand vp run -r build
executeCommand vp run -r test

echo ""
echo "✅ Commands executed successfully"
