#!/usr/bin/env bash
#MISE description="Run the containerized Dagger pipeline (same one CI runs)"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."

cd "${rootDir}"

target="${1:-"ready"}"
shift || true

dagger call "${target}" "${@}"
