#!/usr/bin/env bash
#MISE description="Clean up build artifacts, tools, and AI caches"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

modules="${1:-"true"}"
tools="${2:-"false"}"
ai="${3:-"false"}"
install="${4:-"true"}"

if [[ "${tools}" == "true" ]]; then
  vp run --no-cache clean:tools
fi

if [[ "${ai}" == "true" ]]; then
  vp run --no-cache clean:ai
fi

dagger core engine local-cache prune || true

vp run --no-cache clean:build

if [[ "${modules}" == "true" ]]; then
  vp run --no-cache clean:modules
fi

if [[ "${install}" == "true" ]]; then
  vp install --frozen-lockfile
  dagger develop
fi

echo ""
echo "✅ All good!"
