#!/usr/bin/env bash
#MISE description="Lint commit messages between two refs (defaults to origin/main..HEAD) with commitlint"

set -o errexit # Bail out on any error

from="origin/main"
to="HEAD"

while [[ "${#}" -gt 0 ]]; do
  case "$1" in
    --from=*)
      from="${1#--from=}"
      shift
      ;;
    --from)
      from="${2}"
      shift 2
      ;;
    --to=*)
      to="${1#--to=}"
      shift
      ;;
    --to)
      to="${2}"
      shift 2
      ;;
    *)
      echo "Usage: mise run commitlint [--from=<ref>|--from <ref>] [--to=<ref>|--to <ref>]"
      exit 1
      ;;
  esac
done

vp exec commitlint \
  --from "${from}" \
  --to "${to}" \
  --config commitlint.config.ts \
  --verbose
