#!/usr/bin/env bash
#MISE description="Deploy workspace to cloudflare workers"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

workspace="${1:?"Usage: mise run deploy <workspace> [key=value ...]"}"
buildEnvArgs=("${@:2}")

args=(
  dagger call wrangler
  --workspace="${workspace}"
  --cloudflare-api-token=env:CLOUDFLARE_API_TOKEN
  --cloudflare-account-id=env:CLOUDFLARE_ACCOUNT_ID
)

for buildEnv in "${buildEnvArgs[@]}"; do
  args+=(--build-env="${buildEnv}")
done

"${args[@]}"
