#!/usr/bin/env bash
#MISE description="Run all the services with docker"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

app="${1:-""}"

dockerSocket="${DOCKER_SOCKET:-"/var/run/docker.sock"}"

projects=(
  "@lightproject/design-system"
  "@lightproject/backend"
  "@lightproject/frontend"
)

if [[ -n "${app}" ]]; then
  projects=("@lightproject/${app}")
fi

for project in "${projects[@]}"; do
  name="${project##*/}"

  storybookPort=""
  containerPort="80"
  storybookContainerPort="81"
  buildArgs=()
  case "${name}" in
    "backend")
      port="${API_PORT:-"3000"}"
      containerPort="3000"
      ;;
    "frontend")
      port="${ADMIN_PORT:-"3001"}"
      buildArgs+=(
        --build-env="VITE_API_URL=${VITE_API_URL}"
      )
      ;;
    "design-system")
      port="${DESIGN_SYSTEM_PORT:-"6007"}"
      storybookPort="${STORYBOOK_PORT:-"6006"}"
      ;;
    *)
      echo "Invalid project: ${project}"
      exit 1
      ;;
  esac

  buildArgs+=(
    --workspace="${project}"
    --docker-socket="${dockerSocket}"
  )

  echo "Building: ${project}"

  dagger call load "${buildArgs[@]}"

  docker rm -f "${name}" || true

  if [[ -n "${storybookPort}" ]]; then
    docker run --rm -d \
      -p "${port}:${containerPort}" \
      -p "${storybookPort}:${storybookContainerPort}" \
      --name "${name}" "${name}"
  else
    docker run --rm -d \
      -p "${port}:${containerPort}" \
      --name "${name}" "${name}"
  fi

  echo "✅ ${name} is running on http://localhost:${port}"

  if [[ -n "${storybookPort}" ]]; then
    echo "✅ storybook is running on http://localhost:${storybookPort}"
  fi
done

echo "✅ All good!"
