#!/usr/bin/env bash
#MISE description="Build image for a workspace and load it into the local Docker daemon"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

workspace="${1:?"Usage: mise run load-image <workspace> [tag]"}"
tag="${2:-""}"

dockerSocket="${DOCKER_SOCKET:-"/var/run/docker.sock"}"

args=(dagger call load --workspace="${workspace}" --docker-socket="${dockerSocket}")

if [[ -n "${tag}" ]]; then
  args+=(--tag="${tag}")
fi

"${args[@]}"
