#!/usr/bin/env bash
#MISE description="Start the dev or prod server"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

mode="${1:-"dev"}"

if [[ "${mode}" != "dev" && "${mode}" != "prod" ]]; then
  echo "Invalid mode: ${mode}"
  exit 1
fi

echo "Mode: ${mode}"
vp run "serve:${mode}"
