#!/usr/bin/env bash
#MISE description="Start the dev, prod, or wrangler server"

set -o errexit # Bail out on any error

mode="${1:-"dev"}"

if [[ "${mode}" != "dev" && "${mode}" != "prod" && "${mode}" != "wrangler" ]]; then
  echo "Invalid mode: ${mode}"
  exit 1
fi

echo "Mode: ${mode}"
vp run "serve:${mode}"
