#!/usr/bin/env bash
#MISE description="Stop all the services"

set -o errexit # Bail out on any error

executingDir=$(pwd)
currentDir=$(cd -P -- "$(dirname -- "${0}")" && pwd -P)
scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

rootDir="${scriptDir}/../.."
cd "${rootDir}"

app="${1:-""}"

projects=(
  "@lightproject/design-system"
  "@lightproject/backend"
  "@lightproject/frontend"
)

if [[ -n "${app}" ]]; then
  projects=("@lightproject/${app}")
fi

for project in "${projects[@]}"; do
  name="${project##*/}"

  echo "Stopping: ${project}"

  docker rm -f "${name}" || true

  echo "✅ ${name} is stopped"
done

echo "✅ All good!"
