name = "lightproject-design-system"
compatibility_date = "2026-08-26"

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true
invocation_logs = true
persist = true

[observability.traces]
enabled = true
persist = true
