extensions:
  file_storage:
    directory: /var/lib/otelcol/file_storage
    create_directory: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - 'http://*'
            - 'https://*'
          allowed_headers:
            - '*'

  faro:
    endpoint: 0.0.0.0:12347
    cors:
      allowed_origins:
        - 'http://*'
        - 'https://*'
      allowed_headers:
        - '*'

processors:
  resource/metrics:
    attributes:
      - key: service_name
        from_attribute: service.name
        action: upsert

  resource/default:
    attributes:
      - key: deployment.environment
        action: upsert
        value: local

  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push

  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    sending_queue:
      storage: file_storage

  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
    sending_queue:
      storage: file_storage

  debug:
    verbosity: detailed

service:
  extensions:
    - file_storage

  telemetry:
    logs:
      level: info

  pipelines:
    metrics:
      exporters:
        - prometheusremotewrite
        - debug
      processors:
        - resource/metrics
        - batch
      receivers:
        - otlp

    logs:
      exporters:
        - otlphttp/loki
        - debug
      processors:
        - resource/default
        - batch
      receivers:
        - otlp
        - faro

    traces:
      exporters:
        - otlp/tempo
        - debug
      processors:
        - resource/default
        - batch
      receivers:
        - otlp
        - faro
