
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Round` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Round
 * 
 */
export type RoundModel = runtime.Types.Result.DefaultSelection<Prisma.$RoundPayload>

export type AggregateRound = {
  _count: RoundCountAggregateOutputType | null
  _avg: RoundAvgAggregateOutputType | null
  _sum: RoundSumAggregateOutputType | null
  _min: RoundMinAggregateOutputType | null
  _max: RoundMaxAggregateOutputType | null
}

export type RoundAvgAggregateOutputType = {
  bearAmount: number | null
  bullAmount: number | null
  closeOracleId: number | null
  closePrice: number | null
  closeTimestamp: number | null
  epoch: number | null
  lockOracleId: number | null
  lockPrice: number | null
  lockTimestamp: number | null
  rewardAmount: number | null
  rewardBaseCalAmount: number | null
  startTimestamp: number | null
  totalAmount: number | null
}

export type RoundSumAggregateOutputType = {
  bearAmount: number | null
  bullAmount: number | null
  closeOracleId: number | null
  closePrice: number | null
  closeTimestamp: number | null
  epoch: number | null
  lockOracleId: number | null
  lockPrice: number | null
  lockTimestamp: number | null
  rewardAmount: number | null
  rewardBaseCalAmount: number | null
  startTimestamp: number | null
  totalAmount: number | null
}

export type RoundMinAggregateOutputType = {
  id: string | null
  bearAmount: number | null
  bullAmount: number | null
  closeOracleId: number | null
  closePrice: number | null
  closeTimestamp: number | null
  epoch: number | null
  lockOracleId: number | null
  lockPrice: number | null
  lockTimestamp: number | null
  oracleCalled: boolean | null
  rewardAmount: number | null
  rewardBaseCalAmount: number | null
  startTimestamp: number | null
  totalAmount: number | null
}

export type RoundMaxAggregateOutputType = {
  id: string | null
  bearAmount: number | null
  bullAmount: number | null
  closeOracleId: number | null
  closePrice: number | null
  closeTimestamp: number | null
  epoch: number | null
  lockOracleId: number | null
  lockPrice: number | null
  lockTimestamp: number | null
  oracleCalled: boolean | null
  rewardAmount: number | null
  rewardBaseCalAmount: number | null
  startTimestamp: number | null
  totalAmount: number | null
}

export type RoundCountAggregateOutputType = {
  id: number
  bearAmount: number
  bullAmount: number
  closeOracleId: number
  closePrice: number
  closeTimestamp: number
  epoch: number
  lockOracleId: number
  lockPrice: number
  lockTimestamp: number
  oracleCalled: number
  rewardAmount: number
  rewardBaseCalAmount: number
  startTimestamp: number
  totalAmount: number
  _all: number
}


export type RoundAvgAggregateInputType = {
  bearAmount?: true
  bullAmount?: true
  closeOracleId?: true
  closePrice?: true
  closeTimestamp?: true
  epoch?: true
  lockOracleId?: true
  lockPrice?: true
  lockTimestamp?: true
  rewardAmount?: true
  rewardBaseCalAmount?: true
  startTimestamp?: true
  totalAmount?: true
}

export type RoundSumAggregateInputType = {
  bearAmount?: true
  bullAmount?: true
  closeOracleId?: true
  closePrice?: true
  closeTimestamp?: true
  epoch?: true
  lockOracleId?: true
  lockPrice?: true
  lockTimestamp?: true
  rewardAmount?: true
  rewardBaseCalAmount?: true
  startTimestamp?: true
  totalAmount?: true
}

export type RoundMinAggregateInputType = {
  id?: true
  bearAmount?: true
  bullAmount?: true
  closeOracleId?: true
  closePrice?: true
  closeTimestamp?: true
  epoch?: true
  lockOracleId?: true
  lockPrice?: true
  lockTimestamp?: true
  oracleCalled?: true
  rewardAmount?: true
  rewardBaseCalAmount?: true
  startTimestamp?: true
  totalAmount?: true
}

export type RoundMaxAggregateInputType = {
  id?: true
  bearAmount?: true
  bullAmount?: true
  closeOracleId?: true
  closePrice?: true
  closeTimestamp?: true
  epoch?: true
  lockOracleId?: true
  lockPrice?: true
  lockTimestamp?: true
  oracleCalled?: true
  rewardAmount?: true
  rewardBaseCalAmount?: true
  startTimestamp?: true
  totalAmount?: true
}

export type RoundCountAggregateInputType = {
  id?: true
  bearAmount?: true
  bullAmount?: true
  closeOracleId?: true
  closePrice?: true
  closeTimestamp?: true
  epoch?: true
  lockOracleId?: true
  lockPrice?: true
  lockTimestamp?: true
  oracleCalled?: true
  rewardAmount?: true
  rewardBaseCalAmount?: true
  startTimestamp?: true
  totalAmount?: true
  _all?: true
}

export type RoundAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Round to aggregate.
   */
  where?: Prisma.RoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rounds to fetch.
   */
  orderBy?: Prisma.RoundOrderByWithRelationInput | Prisma.RoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Rounds
  **/
  _count?: true | RoundCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RoundAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RoundSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RoundMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RoundMaxAggregateInputType
}

export type GetRoundAggregateType<T extends RoundAggregateArgs> = {
      [P in keyof T & keyof AggregateRound]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRound[P]>
    : Prisma.GetScalarType<T[P], AggregateRound[P]>
}




export type RoundGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoundWhereInput
  orderBy?: Prisma.RoundOrderByWithAggregationInput | Prisma.RoundOrderByWithAggregationInput[]
  by: Prisma.RoundScalarFieldEnum[] | Prisma.RoundScalarFieldEnum
  having?: Prisma.RoundScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RoundCountAggregateInputType | true
  _avg?: RoundAvgAggregateInputType
  _sum?: RoundSumAggregateInputType
  _min?: RoundMinAggregateInputType
  _max?: RoundMaxAggregateInputType
}

export type RoundGroupByOutputType = {
  id: string
  bearAmount: number
  bullAmount: number
  closeOracleId: number
  closePrice: number
  closeTimestamp: number
  epoch: number
  lockOracleId: number
  lockPrice: number
  lockTimestamp: number
  oracleCalled: boolean
  rewardAmount: number
  rewardBaseCalAmount: number
  startTimestamp: number
  totalAmount: number
  _count: RoundCountAggregateOutputType | null
  _avg: RoundAvgAggregateOutputType | null
  _sum: RoundSumAggregateOutputType | null
  _min: RoundMinAggregateOutputType | null
  _max: RoundMaxAggregateOutputType | null
}

type GetRoundGroupByPayload<T extends RoundGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RoundGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RoundGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RoundGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RoundGroupByOutputType[P]>
      }
    >
  > 



export type RoundWhereInput = {
  AND?: Prisma.RoundWhereInput | Prisma.RoundWhereInput[]
  OR?: Prisma.RoundWhereInput[]
  NOT?: Prisma.RoundWhereInput | Prisma.RoundWhereInput[]
  id?: Prisma.StringFilter<"Round"> | string
  bearAmount?: Prisma.FloatFilter<"Round"> | number
  bullAmount?: Prisma.FloatFilter<"Round"> | number
  closeOracleId?: Prisma.IntFilter<"Round"> | number
  closePrice?: Prisma.FloatFilter<"Round"> | number
  closeTimestamp?: Prisma.IntFilter<"Round"> | number
  epoch?: Prisma.IntFilter<"Round"> | number
  lockOracleId?: Prisma.IntFilter<"Round"> | number
  lockPrice?: Prisma.FloatFilter<"Round"> | number
  lockTimestamp?: Prisma.IntFilter<"Round"> | number
  oracleCalled?: Prisma.BoolFilter<"Round"> | boolean
  rewardAmount?: Prisma.FloatFilter<"Round"> | number
  rewardBaseCalAmount?: Prisma.FloatFilter<"Round"> | number
  startTimestamp?: Prisma.IntFilter<"Round"> | number
  totalAmount?: Prisma.FloatFilter<"Round"> | number
}

export type RoundOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  oracleCalled?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type RoundWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RoundWhereInput | Prisma.RoundWhereInput[]
  OR?: Prisma.RoundWhereInput[]
  NOT?: Prisma.RoundWhereInput | Prisma.RoundWhereInput[]
  bearAmount?: Prisma.FloatFilter<"Round"> | number
  bullAmount?: Prisma.FloatFilter<"Round"> | number
  closeOracleId?: Prisma.IntFilter<"Round"> | number
  closePrice?: Prisma.FloatFilter<"Round"> | number
  closeTimestamp?: Prisma.IntFilter<"Round"> | number
  epoch?: Prisma.IntFilter<"Round"> | number
  lockOracleId?: Prisma.IntFilter<"Round"> | number
  lockPrice?: Prisma.FloatFilter<"Round"> | number
  lockTimestamp?: Prisma.IntFilter<"Round"> | number
  oracleCalled?: Prisma.BoolFilter<"Round"> | boolean
  rewardAmount?: Prisma.FloatFilter<"Round"> | number
  rewardBaseCalAmount?: Prisma.FloatFilter<"Round"> | number
  startTimestamp?: Prisma.IntFilter<"Round"> | number
  totalAmount?: Prisma.FloatFilter<"Round"> | number
}, "id">

export type RoundOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  oracleCalled?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  _count?: Prisma.RoundCountOrderByAggregateInput
  _avg?: Prisma.RoundAvgOrderByAggregateInput
  _max?: Prisma.RoundMaxOrderByAggregateInput
  _min?: Prisma.RoundMinOrderByAggregateInput
  _sum?: Prisma.RoundSumOrderByAggregateInput
}

export type RoundScalarWhereWithAggregatesInput = {
  AND?: Prisma.RoundScalarWhereWithAggregatesInput | Prisma.RoundScalarWhereWithAggregatesInput[]
  OR?: Prisma.RoundScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RoundScalarWhereWithAggregatesInput | Prisma.RoundScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Round"> | string
  bearAmount?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  bullAmount?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  closeOracleId?: Prisma.IntWithAggregatesFilter<"Round"> | number
  closePrice?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  closeTimestamp?: Prisma.IntWithAggregatesFilter<"Round"> | number
  epoch?: Prisma.IntWithAggregatesFilter<"Round"> | number
  lockOracleId?: Prisma.IntWithAggregatesFilter<"Round"> | number
  lockPrice?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  lockTimestamp?: Prisma.IntWithAggregatesFilter<"Round"> | number
  oracleCalled?: Prisma.BoolWithAggregatesFilter<"Round"> | boolean
  rewardAmount?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  rewardBaseCalAmount?: Prisma.FloatWithAggregatesFilter<"Round"> | number
  startTimestamp?: Prisma.IntWithAggregatesFilter<"Round"> | number
  totalAmount?: Prisma.FloatWithAggregatesFilter<"Round"> | number
}

export type RoundCreateInput = {
  id?: string
  bearAmount: number
  bullAmount: number
  closeOracleId: number
  closePrice: number
  closeTimestamp: number
  epoch: number
  lockOracleId: number
  lockPrice: number
  lockTimestamp: number
  oracleCalled: boolean
  rewardAmount: number
  rewardBaseCalAmount: number
  startTimestamp: number
  totalAmount: number
}

export type RoundUncheckedCreateInput = {
  id?: string
  bearAmount: number
  bullAmount: number
  closeOracleId: number
  closePrice: number
  closeTimestamp: number
  epoch: number
  lockOracleId: number
  lockPrice: number
  lockTimestamp: number
  oracleCalled: boolean
  rewardAmount: number
  rewardBaseCalAmount: number
  startTimestamp: number
  totalAmount: number
}

export type RoundUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bearAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  bullAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  closeOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  closePrice?: Prisma.FloatFieldUpdateOperationsInput | number
  closeTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  epoch?: Prisma.IntFieldUpdateOperationsInput | number
  lockOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  lockPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  lockTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  oracleCalled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rewardAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  rewardBaseCalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  startTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoundUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bearAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  bullAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  closeOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  closePrice?: Prisma.FloatFieldUpdateOperationsInput | number
  closeTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  epoch?: Prisma.IntFieldUpdateOperationsInput | number
  lockOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  lockPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  lockTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  oracleCalled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rewardAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  rewardBaseCalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  startTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoundCreateManyInput = {
  id?: string
  bearAmount: number
  bullAmount: number
  closeOracleId: number
  closePrice: number
  closeTimestamp: number
  epoch: number
  lockOracleId: number
  lockPrice: number
  lockTimestamp: number
  oracleCalled: boolean
  rewardAmount: number
  rewardBaseCalAmount: number
  startTimestamp: number
  totalAmount: number
}

export type RoundUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bearAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  bullAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  closeOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  closePrice?: Prisma.FloatFieldUpdateOperationsInput | number
  closeTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  epoch?: Prisma.IntFieldUpdateOperationsInput | number
  lockOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  lockPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  lockTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  oracleCalled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rewardAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  rewardBaseCalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  startTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoundUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bearAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  bullAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  closeOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  closePrice?: Prisma.FloatFieldUpdateOperationsInput | number
  closeTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  epoch?: Prisma.IntFieldUpdateOperationsInput | number
  lockOracleId?: Prisma.IntFieldUpdateOperationsInput | number
  lockPrice?: Prisma.FloatFieldUpdateOperationsInput | number
  lockTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  oracleCalled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rewardAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  rewardBaseCalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  startTimestamp?: Prisma.IntFieldUpdateOperationsInput | number
  totalAmount?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type RoundCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  oracleCalled?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type RoundAvgOrderByAggregateInput = {
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type RoundMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  oracleCalled?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type RoundMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  oracleCalled?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type RoundSumOrderByAggregateInput = {
  bearAmount?: Prisma.SortOrder
  bullAmount?: Prisma.SortOrder
  closeOracleId?: Prisma.SortOrder
  closePrice?: Prisma.SortOrder
  closeTimestamp?: Prisma.SortOrder
  epoch?: Prisma.SortOrder
  lockOracleId?: Prisma.SortOrder
  lockPrice?: Prisma.SortOrder
  lockTimestamp?: Prisma.SortOrder
  rewardAmount?: Prisma.SortOrder
  rewardBaseCalAmount?: Prisma.SortOrder
  startTimestamp?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type RoundSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bearAmount?: boolean
  bullAmount?: boolean
  closeOracleId?: boolean
  closePrice?: boolean
  closeTimestamp?: boolean
  epoch?: boolean
  lockOracleId?: boolean
  lockPrice?: boolean
  lockTimestamp?: boolean
  oracleCalled?: boolean
  rewardAmount?: boolean
  rewardBaseCalAmount?: boolean
  startTimestamp?: boolean
  totalAmount?: boolean
}, ExtArgs["result"]["round"]>

export type RoundSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bearAmount?: boolean
  bullAmount?: boolean
  closeOracleId?: boolean
  closePrice?: boolean
  closeTimestamp?: boolean
  epoch?: boolean
  lockOracleId?: boolean
  lockPrice?: boolean
  lockTimestamp?: boolean
  oracleCalled?: boolean
  rewardAmount?: boolean
  rewardBaseCalAmount?: boolean
  startTimestamp?: boolean
  totalAmount?: boolean
}, ExtArgs["result"]["round"]>

export type RoundSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bearAmount?: boolean
  bullAmount?: boolean
  closeOracleId?: boolean
  closePrice?: boolean
  closeTimestamp?: boolean
  epoch?: boolean
  lockOracleId?: boolean
  lockPrice?: boolean
  lockTimestamp?: boolean
  oracleCalled?: boolean
  rewardAmount?: boolean
  rewardBaseCalAmount?: boolean
  startTimestamp?: boolean
  totalAmount?: boolean
}, ExtArgs["result"]["round"]>

export type RoundSelectScalar = {
  id?: boolean
  bearAmount?: boolean
  bullAmount?: boolean
  closeOracleId?: boolean
  closePrice?: boolean
  closeTimestamp?: boolean
  epoch?: boolean
  lockOracleId?: boolean
  lockPrice?: boolean
  lockTimestamp?: boolean
  oracleCalled?: boolean
  rewardAmount?: boolean
  rewardBaseCalAmount?: boolean
  startTimestamp?: boolean
  totalAmount?: boolean
}

export type RoundOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bearAmount" | "bullAmount" | "closeOracleId" | "closePrice" | "closeTimestamp" | "epoch" | "lockOracleId" | "lockPrice" | "lockTimestamp" | "oracleCalled" | "rewardAmount" | "rewardBaseCalAmount" | "startTimestamp" | "totalAmount", ExtArgs["result"]["round"]>

export type $RoundPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Round"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    bearAmount: number
    bullAmount: number
    closeOracleId: number
    closePrice: number
    closeTimestamp: number
    epoch: number
    lockOracleId: number
    lockPrice: number
    lockTimestamp: number
    oracleCalled: boolean
    rewardAmount: number
    rewardBaseCalAmount: number
    startTimestamp: number
    totalAmount: number
  }, ExtArgs["result"]["round"]>
  composites: {}
}

export type RoundGetPayload<S extends boolean | null | undefined | RoundDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RoundPayload, S>

export type RoundCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RoundFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RoundCountAggregateInputType | true
  }

export interface RoundDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Round'], meta: { name: 'Round' } }
  /**
   * Find zero or one Round that matches the filter.
   * @param {RoundFindUniqueArgs} args - Arguments to find a Round
   * @example
   * // Get one Round
   * const round = await prisma.round.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RoundFindUniqueArgs>(args: Prisma.SelectSubset<T, RoundFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Round that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RoundFindUniqueOrThrowArgs} args - Arguments to find a Round
   * @example
   * // Get one Round
   * const round = await prisma.round.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RoundFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RoundFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Round that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundFindFirstArgs} args - Arguments to find a Round
   * @example
   * // Get one Round
   * const round = await prisma.round.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RoundFindFirstArgs>(args?: Prisma.SelectSubset<T, RoundFindFirstArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Round that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundFindFirstOrThrowArgs} args - Arguments to find a Round
   * @example
   * // Get one Round
   * const round = await prisma.round.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RoundFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RoundFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Rounds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Rounds
   * const rounds = await prisma.round.findMany()
   * 
   * // Get first 10 Rounds
   * const rounds = await prisma.round.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const roundWithIdOnly = await prisma.round.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RoundFindManyArgs>(args?: Prisma.SelectSubset<T, RoundFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Round.
   * @param {RoundCreateArgs} args - Arguments to create a Round.
   * @example
   * // Create one Round
   * const Round = await prisma.round.create({
   *   data: {
   *     // ... data to create a Round
   *   }
   * })
   * 
   */
  create<T extends RoundCreateArgs>(args: Prisma.SelectSubset<T, RoundCreateArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Rounds.
   * @param {RoundCreateManyArgs} args - Arguments to create many Rounds.
   * @example
   * // Create many Rounds
   * const round = await prisma.round.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RoundCreateManyArgs>(args?: Prisma.SelectSubset<T, RoundCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Rounds and returns the data saved in the database.
   * @param {RoundCreateManyAndReturnArgs} args - Arguments to create many Rounds.
   * @example
   * // Create many Rounds
   * const round = await prisma.round.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Rounds and only return the `id`
   * const roundWithIdOnly = await prisma.round.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RoundCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RoundCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Round.
   * @param {RoundDeleteArgs} args - Arguments to delete one Round.
   * @example
   * // Delete one Round
   * const Round = await prisma.round.delete({
   *   where: {
   *     // ... filter to delete one Round
   *   }
   * })
   * 
   */
  delete<T extends RoundDeleteArgs>(args: Prisma.SelectSubset<T, RoundDeleteArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Round.
   * @param {RoundUpdateArgs} args - Arguments to update one Round.
   * @example
   * // Update one Round
   * const round = await prisma.round.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RoundUpdateArgs>(args: Prisma.SelectSubset<T, RoundUpdateArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Rounds.
   * @param {RoundDeleteManyArgs} args - Arguments to filter Rounds to delete.
   * @example
   * // Delete a few Rounds
   * const { count } = await prisma.round.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RoundDeleteManyArgs>(args?: Prisma.SelectSubset<T, RoundDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rounds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Rounds
   * const round = await prisma.round.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RoundUpdateManyArgs>(args: Prisma.SelectSubset<T, RoundUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rounds and returns the data updated in the database.
   * @param {RoundUpdateManyAndReturnArgs} args - Arguments to update many Rounds.
   * @example
   * // Update many Rounds
   * const round = await prisma.round.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Rounds and only return the `id`
   * const roundWithIdOnly = await prisma.round.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RoundUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RoundUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Round.
   * @param {RoundUpsertArgs} args - Arguments to update or create a Round.
   * @example
   * // Update or create a Round
   * const round = await prisma.round.upsert({
   *   create: {
   *     // ... data to create a Round
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Round we want to update
   *   }
   * })
   */
  upsert<T extends RoundUpsertArgs>(args: Prisma.SelectSubset<T, RoundUpsertArgs<ExtArgs>>): Prisma.Prisma__RoundClient<runtime.Types.Result.GetResult<Prisma.$RoundPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Rounds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundCountArgs} args - Arguments to filter Rounds to count.
   * @example
   * // Count the number of Rounds
   * const count = await prisma.round.count({
   *   where: {
   *     // ... the filter for the Rounds we want to count
   *   }
   * })
  **/
  count<T extends RoundCountArgs>(
    args?: Prisma.Subset<T, RoundCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RoundCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Round.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RoundAggregateArgs>(args: Prisma.Subset<T, RoundAggregateArgs>): Prisma.PrismaPromise<GetRoundAggregateType<T>>

  /**
   * Group by Round.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoundGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RoundGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RoundGroupByArgs['orderBy'] }
      : { orderBy?: RoundGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RoundGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRoundGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Round model
 */
readonly fields: RoundFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Round.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoundClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Round model
 */
export interface RoundFieldRefs {
  readonly id: Prisma.FieldRef<"Round", 'String'>
  readonly bearAmount: Prisma.FieldRef<"Round", 'Float'>
  readonly bullAmount: Prisma.FieldRef<"Round", 'Float'>
  readonly closeOracleId: Prisma.FieldRef<"Round", 'Int'>
  readonly closePrice: Prisma.FieldRef<"Round", 'Float'>
  readonly closeTimestamp: Prisma.FieldRef<"Round", 'Int'>
  readonly epoch: Prisma.FieldRef<"Round", 'Int'>
  readonly lockOracleId: Prisma.FieldRef<"Round", 'Int'>
  readonly lockPrice: Prisma.FieldRef<"Round", 'Float'>
  readonly lockTimestamp: Prisma.FieldRef<"Round", 'Int'>
  readonly oracleCalled: Prisma.FieldRef<"Round", 'Boolean'>
  readonly rewardAmount: Prisma.FieldRef<"Round", 'Float'>
  readonly rewardBaseCalAmount: Prisma.FieldRef<"Round", 'Float'>
  readonly startTimestamp: Prisma.FieldRef<"Round", 'Int'>
  readonly totalAmount: Prisma.FieldRef<"Round", 'Float'>
}
    

// Custom InputTypes
/**
 * Round findUnique
 */
export type RoundFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter, which Round to fetch.
   */
  where: Prisma.RoundWhereUniqueInput
}

/**
 * Round findUniqueOrThrow
 */
export type RoundFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter, which Round to fetch.
   */
  where: Prisma.RoundWhereUniqueInput
}

/**
 * Round findFirst
 */
export type RoundFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter, which Round to fetch.
   */
  where?: Prisma.RoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rounds to fetch.
   */
  orderBy?: Prisma.RoundOrderByWithRelationInput | Prisma.RoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rounds.
   */
  cursor?: Prisma.RoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rounds.
   */
  distinct?: Prisma.RoundScalarFieldEnum | Prisma.RoundScalarFieldEnum[]
}

/**
 * Round findFirstOrThrow
 */
export type RoundFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter, which Round to fetch.
   */
  where?: Prisma.RoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rounds to fetch.
   */
  orderBy?: Prisma.RoundOrderByWithRelationInput | Prisma.RoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rounds.
   */
  cursor?: Prisma.RoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rounds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rounds.
   */
  distinct?: Prisma.RoundScalarFieldEnum | Prisma.RoundScalarFieldEnum[]
}

/**
 * Round findMany
 */
export type RoundFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter, which Rounds to fetch.
   */
  where?: Prisma.RoundWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rounds to fetch.
   */
  orderBy?: Prisma.RoundOrderByWithRelationInput | Prisma.RoundOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Rounds.
   */
  cursor?: Prisma.RoundWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rounds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rounds.
   */
  skip?: number
  distinct?: Prisma.RoundScalarFieldEnum | Prisma.RoundScalarFieldEnum[]
}

/**
 * Round create
 */
export type RoundCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * The data needed to create a Round.
   */
  data: Prisma.XOR<Prisma.RoundCreateInput, Prisma.RoundUncheckedCreateInput>
}

/**
 * Round createMany
 */
export type RoundCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Rounds.
   */
  data: Prisma.RoundCreateManyInput | Prisma.RoundCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Round createManyAndReturn
 */
export type RoundCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * The data used to create many Rounds.
   */
  data: Prisma.RoundCreateManyInput | Prisma.RoundCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Round update
 */
export type RoundUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * The data needed to update a Round.
   */
  data: Prisma.XOR<Prisma.RoundUpdateInput, Prisma.RoundUncheckedUpdateInput>
  /**
   * Choose, which Round to update.
   */
  where: Prisma.RoundWhereUniqueInput
}

/**
 * Round updateMany
 */
export type RoundUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Rounds.
   */
  data: Prisma.XOR<Prisma.RoundUpdateManyMutationInput, Prisma.RoundUncheckedUpdateManyInput>
  /**
   * Filter which Rounds to update
   */
  where?: Prisma.RoundWhereInput
  /**
   * Limit how many Rounds to update.
   */
  limit?: number
}

/**
 * Round updateManyAndReturn
 */
export type RoundUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * The data used to update Rounds.
   */
  data: Prisma.XOR<Prisma.RoundUpdateManyMutationInput, Prisma.RoundUncheckedUpdateManyInput>
  /**
   * Filter which Rounds to update
   */
  where?: Prisma.RoundWhereInput
  /**
   * Limit how many Rounds to update.
   */
  limit?: number
}

/**
 * Round upsert
 */
export type RoundUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * The filter to search for the Round to update in case it exists.
   */
  where: Prisma.RoundWhereUniqueInput
  /**
   * In case the Round found by the `where` argument doesn't exist, create a new Round with this data.
   */
  create: Prisma.XOR<Prisma.RoundCreateInput, Prisma.RoundUncheckedCreateInput>
  /**
   * In case the Round was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RoundUpdateInput, Prisma.RoundUncheckedUpdateInput>
}

/**
 * Round delete
 */
export type RoundDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
  /**
   * Filter which Round to delete.
   */
  where: Prisma.RoundWhereUniqueInput
}

/**
 * Round deleteMany
 */
export type RoundDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Rounds to delete
   */
  where?: Prisma.RoundWhereInput
  /**
   * Limit how many Rounds to delete.
   */
  limit?: number
}

/**
 * Round without action
 */
export type RoundDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Round
   */
  select?: Prisma.RoundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Round
   */
  omit?: Prisma.RoundOmit<ExtArgs> | null
}
