name: 'Workspace Checks'

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run (develop, staging, production)'
        required: true
        type: string

jobs:
  checks:
    name: ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - design-system
          - frontend
          - backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Run dagger pipeline
        uses: ./.github/actions/main
        with:
          workspace: '@lightproject/${{ matrix.workspace }}'
          environment: ${{ inputs.environment }}
