name: 'Workspace Checks'

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment to run against (develop, staging, production)'
        required: true
        type: string

jobs:
  checks:
    name: ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - '@lightproject/backend'
          - '@lightproject/frontend'
          - '@lightproject/design-system'
    permissions:
      contents: read
      actions: write
    steps:
      - name: Run dagger pipeline
        uses: ./.github/actions/main
        with:
          environment: ${{ inputs.environment }}
