name: 'CI'

on:
  push:
    branches: [develop, main]
jobs:
  # ready:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     actions: write
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7.0.1

  #     - name: Base setup
  #       uses: ./.github/actions/base

  develop:
    if: github.ref == 'refs/heads/develop'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/shared/workspace-checks.yml
    with:
      environment: develop
    secrets: inherit

  staging:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/shared/workspace-checks.yml
    with:
      environment: staging
    secrets: inherit

  production:
    needs: staging
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/shared/workspace-checks.yml
    with:
      environment: production
    secrets: inherit
