name: 'Main'

on:
  push:
    branches: [main]
  workflow_call:

concurrency:
  group: main
  cancel-in-progress: false

jobs:
  develop:
    name: 'Develop'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: develop

  staging:
    name: 'Staging'
    needs: develop
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: staging

  production:
    name: 'Production'
    needs: staging
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: production
