name: 'Main'

on:
  push:
    branches: [main]

jobs:
  validate:
    name: Validate
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/validate.yml

  develop:
    name: Develop
    needs: validate
    concurrency:
      group: deploy-develop
      cancel-in-progress: true
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: develop
