name: 'Main Pipeline'

on:
  push:
    branches: [main]

concurrency:
  group: main
  cancel-in-progress: false

jobs:
  develop:
    name: 'Develop'
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: develop
    secrets: inherit

  staging:
    name: 'Staging'
    needs: develop
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: staging
    secrets: inherit

  production:
    name: 'Production'
    needs: staging
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/check.yml
    with:
      environment: production
    secrets: inherit
