name: 'Main'

on:
  push:
    branches: [main]

jobs:
  # scan:
  #   name: Scan
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   uses: ./.github/workflows/scan.yml

  develop:
    name: Develop
    # needs: scan
    concurrency:
      group: deploy-develop
      cancel-in-progress: true
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: develop
