name: 'PR'

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # validate:
  #   name: Validate
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   uses: ./.github/workflows/validate.yml

  pull-request:
    name: 'PR #${{ github.event.pull_request.number }} (branch: ${{ github.head_ref }})'
    # needs: validate
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: pr
