name: 'PR'

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/_main.yml
    with:
      cacheScope: ${{ github.head_ref }}
    secrets: inherit
