name: 'Trigger'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - pr
          - develop
          - staging
          - production
      workspace:
        description: 'Workspace'
        required: true
        type: choice
        default: all
        options:
          - all
          - design-system
          - frontend
          - backend

concurrency:
  group: trigger-${{ inputs.environment }}${{ inputs.environment == 'pr' && format('-{0}', github.ref) || '' }}
  cancel-in-progress: false

jobs:
  trigger:
    name: 'Trigger (branch: ${{ github.ref_name }} | environment: ${{ inputs.environment }})'
    if: |
      (inputs.environment == 'pr' && github.ref != 'refs/heads/main') ||
      (inputs.environment != 'pr' && github.ref == 'refs/heads/main')
    permissions:
      contents: read
      actions: write
      pull-requests: write
    uses: ./.github/workflows/check.yml
    with:
      environment: ${{ inputs.environment }}
      workspace: ${{ inputs.workspace != 'all' && inputs.workspace || '' }}
